/**
 * Purus - A language that compiles to JavaScript
 *
 * This module provides a programmatic API for compiling Purus source code
 * to JavaScript. Works in both CommonJS and ES Module environments.
 *
 * @example
 * // ESM
 * import { compile } from 'purus';
 * const js = compile('const x be 42');
 *
 * // CJS
 * const { compile } = require('purus');
 * const js = compile('const x be 42');
 */

"use strict";

const core = require("./lib/purus-core.js");

/**
 * Compile Purus source code to JavaScript.
 *
 * @param {string} source - Purus source code
 * @param {Object} [options] - Compilation options
 * @param {boolean} [options.header=true] - Include "Generated by Purus" header comment
 * @returns {string} Generated JavaScript code
 */
function compile(source, options) {
  return core.compile(source, options);
}

/**
 * Check Purus source code for syntax errors.
 *
 * @param {string} source - Purus source code
 * @returns {true} Returns true if syntax is valid
 * @throws {Error} If syntax is invalid
 */
function check(source) {
  return core.check(source);
}

/** @type {string} The Purus compiler version */
const version = core.version;

module.exports = { compile, check, version };
